# Generated by Django 5.1.4 on 2025-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
