# Generated by Django 5.2.6 on 2025-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
